### ISSUE TITLE
New README.md

### ISSUE THREAD

**Issue by arturoBeccar** [aprendiendoenloprofundo/redes-neuronales-y-aprendiendo-en-lo-profundo#1]
Delete old readme and make a readme with these sections.

- Redes neuronales y aprendiendo en lo profundo (titulo principal) (add mit badge here)
- Descripcion (primer subtitulo) Poner una descricion breve de lo que estamos haciendo, hacer videos resumiendo los capitulos al espaniol y mostrar como correr el codigo.
- Capitulos (segundo subtitulo) Poner una descripcion enumerando los capitulos y donde vamos a poner links a cada nuevo video de youtube
- Reconocimientos (tercer subtitulo) Poner una descripcion indicando que este es un fork de un proyecto de alguien mas que a su vez forkea a michael nealsen
- Licencia (cuarto subtitulo) Poner una descripcion de la licencia que usamos. (ver como se hace en otros repos https://github.com/CoinFabrik/scout)

**Comment by BautistaAcosta** [comment]
Done

**Comment by arturoBeccar** [comment]
- [x] Create a new branch clicking on the `Create a branch` link, and work on a new branch.

![image](https://github.com/user-attachments/assets/9744f052-7920-45ad-adb7-55a67a3f5339)

- [x] Edit the README.md removing old contents and replacing them with the content in README_nuevo.md

- [x] Delete README_nuevo.md

- [ ] When done make a PR to merge the new branch with  main.
